@extends('admin.layouts.app')
@section('content')
<div class="app-content-header"><div class="container-fluid"><h1>Nova assinatura eletrônica</h1></div></div>
<div class="app-content"><div class="container-fluid"><form method="POST" action="{{ route('admin.signature-requests.store') }}" class="card"><div class="card-body row g-3">@csrf
<div class="col-md-6"><label class="form-label">Documento</label><select name="legal_document_id" class="form-select" required><option value="">Selecione</option>@foreach($documents as $document)<option value="{{ $document->id }}" @selected(old('legal_document_id', $selectedDocument) == $document->id)>{{ $document->title }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Título</label><input name="title" class="form-control" maxlength="255" required></div>
<div class="col-md-6"><label class="form-label">Expira em</label><input type="datetime-local" name="expires_at" class="form-control" value="{{ now()->addDays(config('signatures.default_expiration_days'))->format('Y-m-d\TH:i') }}" required></div>
<div class="col-md-6 d-flex align-items-end"><div class="form-check"><input type="hidden" name="ordered" value="0"><input type="checkbox" name="ordered" value="1" class="form-check-input" id="ordered"><label for="ordered" class="form-check-label">Exigir ordem dos signatários</label></div></div>
<div class="col-12"><label class="form-label">Mensagem</label><textarea name="message" class="form-control" rows="3"></textarea></div>
<div class="col-12"><div class="d-flex justify-content-between"><label class="form-label">Signatários</label><button type="button" class="btn btn-sm btn-outline-primary" id="add-signer">Adicionar</button></div><div id="signers"><div class="row g-2 mb-2 signer-row"><div class="col-md-4"><input name="signers[0][name]" class="form-control" placeholder="Nome completo" required></div><div class="col-md-4"><input type="email" name="signers[0][email]" class="form-control" placeholder="E-mail" required></div><div class="col-md-3"><input name="signers[0][document]" class="form-control" data-mask="cpf-cnpj" placeholder="CPF/CNPJ"></div><div class="col-md-1"><button type="button" class="btn btn-outline-danger remove-signer" disabled>×</button></div></div></div><small class="text-muted">Até 20 signatários; a ordem exibida será a ordem de assinatura.</small></div>
</div><div class="card-footer text-end"><button class="btn btn-primary">Criar e enviar</button></div></form></div></div>
@endsection
@push('scripts')<script>document.getElementById('add-signer')?.addEventListener('click',()=>{const box=document.getElementById('signers');if(box.children.length>=20)return;const row=box.firstElementChild.cloneNode(true);const index=box.children.length;row.querySelectorAll('input').forEach(input=>{input.value='';input.name=input.name.replace(/signers\[\d+\]/,`signers[${index}]`)});row.querySelector('.remove-signer').disabled=false;box.appendChild(row)});document.getElementById('signers')?.addEventListener('click',event=>{if(event.target.classList.contains('remove-signer'))event.target.closest('.signer-row').remove()});</script>@endpush
